// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-0pEeq2JfzAnonj3jRqYFUHp8_M2hd54',
    appId: '1:1094607371089:web:957366b6d1c2c53da5b170',
    messagingSenderId: '1094607371089',
    projectId: 'employee-db-a06b2',
    authDomain: 'employee-db-a06b2.firebaseapp.com',
    databaseURL: 'https://employee-db-a06b2-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-a06b2.firebasestorage.app',
    measurementId: 'G-MYP10WHY7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChamOPgDY_Yaf9zYBuoRaQpsEKoSK7mvU',
    appId: '1:1094607371089:android:4fbb09de7199743ba5b170',
    messagingSenderId: '1094607371089',
    projectId: 'employee-db-a06b2',
    databaseURL: 'https://employee-db-a06b2-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-a06b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3P54UEDLNKNAY4S0ogXwZPlkrE92HfM',
    appId: '1:1094607371089:ios:fd4c12c8eacd858ba5b170',
    messagingSenderId: '1094607371089',
    projectId: 'employee-db-a06b2',
    databaseURL: 'https://employee-db-a06b2-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-a06b2.firebasestorage.app',
    iosBundleId: 'com.example.employeeWildan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq3P54UEDLNKNAY4S0ogXwZPlkrE92HfM',
    appId: '1:1094607371089:ios:fd4c12c8eacd858ba5b170',
    messagingSenderId: '1094607371089',
    projectId: 'employee-db-a06b2',
    databaseURL: 'https://employee-db-a06b2-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-a06b2.firebasestorage.app',
    iosBundleId: 'com.example.employeeWildan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-0pEeq2JfzAnonj3jRqYFUHp8_M2hd54',
    appId: '1:1094607371089:web:e259386179e8219aa5b170',
    messagingSenderId: '1094607371089',
    projectId: 'employee-db-a06b2',
    authDomain: 'employee-db-a06b2.firebaseapp.com',
    databaseURL: 'https://employee-db-a06b2-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-a06b2.firebasestorage.app',
    measurementId: 'G-CV55W67ZJ8',
  );

}